name: "Cut Release Branch"

on:
  workflow_dispatch: # allow manual triggering
  schedule:
    - cron: "0 55 14 ? * THU *" # trigger every Thursday at 14:55 UTC (9:55 EST)

jobs:
  cut-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compute branch name
        id: branch_name
        run: echo "branch_name=release-$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - run: |
          git checkout -b ${{ steps.branch_name.outputs.branch_name }}
          git push -u origin ${{ steps.branch_name.outputs.branch_name }}
      - run: gh pr --base main --head ${{ steps.branch_name.outputs.branch_name }}}} --title "Release ${{ steps.branch_name.outputs.branch_name }}"
