name: Prerelease

on:
  push:
    branches:
      - 594-set-up-pre-release-branch
jobs:
  prerelease:
    if: github.repository == 'evidence-dev/evidence'
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.23.2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Publish tag:next to npm registry
        run: pnpm run release:next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}