name: 'My Workflow'

on:
  pull_request:

jobs:
  external-pr-action-approval:
    uses: ./.github/workflows/external-pr-action-approval.yml
  my-job:
    needs: external-pr-action-approval
    runs-on: ubuntu-latest
    steps:
      - run: echo "My job ran"