name: UI-Tests
on:
  pull_request:
    branches: [main]

jobs:
  wait_for_preview:
    name: Wait for vercel-preview
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for preview-deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 180
          check_interval: 5
  tests:
    name: UI Tests
    needs: wait_for_preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browser
        run: npx playwright install --with-deps
      - name: Run UI Tests
        run: pnpm run test:ui
        env:
          BASE_URL: ${{ needs.wait_for_preview.outputs.preview_url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30